refactor: Party CRUD 리팩토링, ArgumentResolver 추가
jjan-project/jjan_back_renewal pull request #42
Opened 2023-07-19 09:12 UTC by kkangh00n

- Party 로직 수정
- 현재 로그인 유저 확인 어노테이션 추가 (jwt 이용)

2023-07-19 14:05 UTC, kkangh00n reviewed
.

2023-07-19 15:37 UTC, 5tr1ker requested changes
토큰에서 사용자 정보를 가져오기 위해서는 JwtProvider 클래스에서 getUserEmail() 메서드를 활용하시면 됩니다.

2023-07-19 15:37 UTC, 5tr1ker commented on src/main/java/com/team/jjan/party/service/PartyService.java
> +    @Transactional(readOnly = true)
클래스에 @Transaction 이 이미 있기 때문에 이 부분에서는 이미 존재하는 트랜잭션을 공유하기 때문에 제거해도 될 꺼 같습니다.

2023-07-19 15:37 UTC, 5tr1ker commented on src/main/java/com/team/jjan/party/service/PartyService.java
> +    }
파티가 제거되었을 때 S3 이미지도 함께 제거하는 메서드도 추가해주실 수 있나요?

업로드 파일 서비스 클래스에서 deleteFile() 메서드에 이미지 uuid 를 주면 될 꺼 같습니다.

2023-07-19 15:37 UTC, 5tr1ker commented on src/main/java/com/team/jjan/party/controller/PartyController.java
> +}
저번에 말씀드린 것 처럼 저희 프론트 팀에서 code , message , data 로 통일해 달라고 하셔서 Common 패키지 안에있는 ResponseMessage 클래스를 활용해주시면 될 꺼 같아요

2023-07-19 15:37 UTC, 5tr1ker commented on src/main/java/com/team/jjan/common/SessionUserArgumentResolver.java
> +}
저희가 JWT 를 활용하여 토큰 기반의 인증 방식을 따르고 있기 때문에 따로 세션을 만들지 않아도 될 꺼 같아요.

2023-07-20 05:38 UTC, kkangh00n commented on src/main/java/com/team/jjan/party/service/PartyService.java
> +    @Transactional(readOnly = true)
조회 시 readonly true 트랜잭션을 따로 열면 조금에 성능 향상이 있다고 들어서 추가했었습니다
이 부분은 지우도록 하겠습니다!!

2023-07-20 05:38 UTC, kkangh00n commented on src/main/java/com/team/jjan/party/service/PartyService.java
> +    }
추가했습니다!

2023-07-20 05:39 UTC, kkangh00n commented on src/main/java/com/team/jjan/party/controller/PartyController.java
> +}
수정했습니다!

2023-07-20 05:44 UTC, kkangh00n commented on src/main/java/com/team/jjan/common/SessionUserArgumentResolver.java
> +}
객체 이름만 SessionUser이고 이 부분은 세션은 이용한 것이 아닌, 토큰을 통해 가져온 유저 정보입니다...!!
헷갈릴 수 있으니 이름은 수정하도록 하겠습니다

2023-07-21 02:51 UTC, 5tr1ker approved these changes

2023-07-21 04:51 UTC, merged