feature: 파티 가입 & 파티 탈퇴 기능 구현
jjan-project/jjan_back_renewal pull request #48
Opened 2023-07-25 01:38 UTC by kkangh00n

- 요구사항에 따라 User와 Party간 M:N 연관관계 매핑 추가
- 응답 정보 수정
- 파티 가입 & 탈퇴 기능 구현 (회의 후 수정 필요)

2023-07-25 05:23 UTC, 5tr1ker requested changes
로직 상 반복되는 부분이 많아서 수정하실 떄 연관된 코드도 함께 수정하시면 될꺼같습니다.

2023-07-25 05:23 UTC, 5tr1ker commented on src/main/java/com/team/jjan/party/entity/PartyEntity.java
> +    @JsonIgnore
반환할 때 엔티티 대신에 DTO를 이용해서 반환하는데 엔티티에 @JsonIgnore 를 사용하신 이유가 궁금합니다

2023-07-25 05:23 UTC, 5tr1ker commented on src/main/java/com/team/jjan/party/service/PartyService.java
>          return ResponseMessage.of(REQUEST_SUCCESS);
DB 서버와 5번 통신하는데 많은 비용이 든다고 생각합니다.

인가를 확인해야 한다면 파티를 찾을 때 접속한 유저가 소유한 파티를 조인해서 찾는 쿼리로 만든다면 위의 3가지 쿼리를 하나로 묶을 수 있다고 생각합니다.

2023-07-25 05:23 UTC, 5tr1ker commented on src/main/java/com/team/jjan/party/service/PartyService.java
>          return ResponseMessage.of(REQUEST_SUCCESS);
select * from 파티 join 유저 on 파티.생성자 아이디 == 유저.아이디

2023-07-25 05:23 UTC, 5tr1ker commented on src/main/java/com/team/jjan/partyJoin/service/PartyJoinService.java
> +}
작성자라면 게시물이 삭제된 상태에서 파티를 떠나게 될텐데 로직상 모순이 있는거같습니다.

2023-07-25 05:23 UTC, 5tr1ker commented on src/main/java/com/team/jjan/partyJoin/service/PartyJoinService.java
> +}
또한 파티에 엔티티에 고아 객체설정이 되어있는데 그걸 활용하면 될꺼같습니다.

2023-07-25 13:47 UTC, kkangh00n commented on src/main/java/com/team/jjan/party/entity/PartyEntity.java
> +    @JsonIgnore
아 이 부분은  객체가 무한 탐색 오류가 발생했을 때 이곳이 오류 부분인 줄 알고 잠시 붙었습니다..!!
불필요한 어노테이션인데 제가 안지웠네요ㅎㅎ

수정하겠습니다!

2023-07-25 14:17 UTC, kkangh00n commented on src/main/java/com/team/jjan/party/service/PartyService.java
>          return ResponseMessage.of(REQUEST_SUCCESS);
넵 조인 추가하였습니다~!

2023-07-25 14:24 UTC, kkangh00n commented on src/main/java/com/team/jjan/partyJoin/service/PartyJoinService.java
> +}
만약 작성자가 파티 탈퇴를 한다면, partyService에서 작성자가 파티를 delete하는 로직을 return해주고 끝납니다.
작성자가 아닌 가입 유저라면,  join정보를 없애고, 끝냅니다.

근데 이 부분은 사실 요구사항을 좀 더 디테일하게 나눠봐야 할 것 같습니다.
작성자가 파티 탈퇴를 하게 되면, 파티가 자체가 삭제되는 것인지 파티장을 넘겨주고 자신만 탈퇴하는 것인지..!!

2023-07-31 07:46 UTC, 5tr1ker approved these changes

2023-07-31 07:52 UTC, merged